version: '3.8'

volumes:
  ai-personal-assistant-data:
    name: ai-personal-assistant-data
  ai-personal-assistant-secrets:
    name: ai-personal-assistant-secrets
  ai-personal-assistant-backups:
    name: ai-personal-assistant-backups

services:
  ai-personal-assistant:
    image: agentscope/ai-personal-assistant:latest
    container_name: ai-personal-assistant
    restart: always
    ports:
      - "127.0.0.1:8088:8088"
    # environment:
    #   - AIPA_AUTH_ENABLED=true
    #   - AIPA_AUTH_USERNAME=admin
    #   - AIPA_AUTH_PASSWORD=yourpassword
    volumes:
      - ai-personal-assistant-data:/app/working
      - ai-personal-assistant-secrets:/app/working.secret
      - ai-personal-assistant-backups:/app/working.backups
